### ISSUE TITLE
Data does not load after changing profile

### ISSUE THREAD

**Issue by Jonn3y** [shayne/hwinfo-streamdeck#14] opened 2020-03-12 10:54 UTC
Hey guys,

i setup the HWInfo plugin and it works good.
But I got the issue, that after changing the Stream Deck Profile to my HW-Info-Profile, some data is not loading.

What is working:
- CPU
- System
- GPU

What is not working:
- HDD/SSD Read/Write
- Network Up/Download
(didn't test  anything else yet!)

After clicking on the individual item in the Stream Deck software, the plugin says "Loading..." and then it works again. 

**HWInfo64 Version:** 6.22

Does anyone else have this issue? 

<img width="433" alt="HWINFO-StreamDeck" src="https://user-images.githubusercontent.com/11927089/76514428-27737880-6458-11ea-915c-1bf706bc2c33.PNG">

**Comment by shayne** [comment] 2020-07-21 01:58
Duplicate of #13

**Closed by shayne** 2020-07-21 01:58 UTC
